import type { SiteContent } from "./types";
import { IMG } from "./placeholder-images";

const now = new Date().toISOString();

export const seedSiteContent: SiteContent = {
  version: 1,
  updatedAt: now,
  settings: {
    siteName: "Eshmart Agrox",
    tagline: "Nigerian Produce. Exported with Integrity.",
    title: "Eshmart Agrox | Premium Nigerian Produce Export",
    description:
      "Premium grade Okra and Ugu exported from Nigeria to European markets with quality and transparency.",
    logoUrl: IMG.hero,
    faviconUrl: "/favicon.ico",
    currency: "NGN",
    currencySymbol: "₦",
    contactEmail: "exports@eshmartagrox.com",
    contactPhone: "+234 800 000 0000",
    address: "12 Export Way, Lagos, Nigeria",
    showSearch: true,
    showCart: true,
    showUser: true,
  },
  navigation: [
    { id: "nav-1", label: "Home", href: "/", order: 1, isVisible: true },
    { id: "nav-2", label: "Portfolio", href: "/portfolio", order: 2, isVisible: true },
    { id: "nav-3", label: "Book Online", href: "/book-online", order: 3, isVisible: true },
    { id: "nav-4", label: "Shop", href: "/shop", order: 4, isVisible: true },
    { id: "nav-5", label: "Blog", href: "/blog", order: 5, isVisible: true },
    {
      id: "nav-6",
      label: "Track My Order",
      href: "/track-my-order",
      order: 6,
      isVisible: true,
    },
  ],
  hero: {
    image: IMG.hero,
    headline: "Nigerian Produce. Exported with Integrity.",
    subheadline:
      "We bridge the gap between Nigeria's finest farms and European markets, delivering premium grade Okra and Ugu with an unwavering commitment to quality and transparency.",
    ctaLabel: "View Our Products",
    ctaHref: "/shop",
    slides: [
      {
        id: "slide-1",
        image: IMG.hero,
        headline: "Nigerian Produce. Exported with Integrity.",
        subheadline:
          "We bridge the gap between Nigeria's finest farms and European markets, delivering premium grade Okra and Ugu with an unwavering commitment to quality and transparency.",
        ctaLabel: "View Our Products",
        ctaHref: "/shop",
      },
    ],
  },
  homeFeatures: {
    sectionTitle: "Our Produce",
    sectionSubtitle:
      "Premium Nigerian harvests meticulously selected for international prestige and exceptional freshness.",
    cards: [
      {
        id: "card-1",
        number: "(01)",
        title: "Export Grade Okra",
        description:
          "Hand-picked for uniform size and vibrant color, ensuring the highest standards for European markets.",
        image: IMG.okra,
        ctaLabel: "Inquire Now",
        ctaHref: "/book-online",
      },
      {
        id: "card-2",
        number: "(02)",
        title: "Premium Ugu Leaves",
        description:
          "Nutrient-dense Nigerian fluted pumpkin leaves, preserved for maximum freshness during rapid transit.",
        image: IMG.greens,
        ctaLabel: "Inquire Now",
        ctaHref: "/book-online",
      },
      {
        id: "card-3",
        number: "(03)",
        title: "Seasonal Specialities",
        description:
          "Beyond our core exports, we curate seasonal Nigerian produce tailored for luxury grocery retailers in Europe.",
        image: IMG.market,
        ctaLabel: "View Availability",
        ctaHref: "/shop",
      },
    ],
  },
  homeQuality: {
    sectionTitle: "Meticulous Cultivation and Export Grade Quality Systems",
    mainImage: IMG.farm,
    secondaryImage: IMG.warehouse,
    blocks: [
      {
        id: "qb-1",
        title: "Ethical Cultivation",
        description:
          "Our okra and ugu cultivation begins with non-GMO seeds and organic soil enrichment, with irrigation systems that prioritize environmental health.",
      },
      {
        id: "qb-2",
        title: "Rigorous Export Audit",
        description:
          "Each harvest undergoes physical uniformity analysis, residue testing, and rapid cooling to meet phytosanitary standards for international trade.",
      },
    ],
  },
  callToAction: {
    title: "Start Your Export Inquiry",
    description:
      "Ready to source premium Nigerian okra and ugu? Share your requirements with our export experts and receive a customized quote.",
    contactImage: IMG.contact,
    secondaryTitle: "From soil to shelf",
    secondaryDescription:
      "End-to-end traceability from Nigerian farms to European distribution partners.",
  },
  footer: {
    copyright: "© 2026 Eshmart Agrox. All rights reserved.",
    socialLinks: [
      { platform: "LinkedIn", url: "https://linkedin.com" },
      { platform: "Instagram", url: "https://instagram.com" },
    ],
    columns: [
      {
        id: "fc-1",
        title: "Company",
        links: [
          { label: "About", href: "/" },
          { label: "Portfolio", href: "/portfolio" },
        ],
      },
      {
        id: "fc-2",
        title: "Shop",
        links: [
          { label: "All Products", href: "/shop" },
          { label: "Okra", href: "/shop" },
        ],
      },
      {
        id: "fc-3",
        title: "Support",
        links: [
          { label: "Book Online", href: "/book-online" },
          { label: "Track Order", href: "/track-my-order" },
        ],
      },
      {
        id: "fc-4",
        title: "Contact",
        links: [
          { label: "exports@eshmartagrox.com", href: "mailto:exports@eshmartagrox.com" },
        ],
      },
    ],
  },
  shop: {
    bannerImage: IMG.shopBanner,
    bannerTitle: "Our Shop",
    sortOptions: [
      "Sort by: Featured",
      "Price: Low to High",
      "Price: High to Low",
      "Name: A to Z",
    ],
    filters: {
      productTypes: ["Okra", "Packaging", "Ugu"],
      priceOptions: ["NGN 8", "NGN 35"],
      lengthOptions: ["100m", "200m"],
      quantityOptions: ["10 Pack", "10 Seedlings", "20 Seedlings", "25 Pack"],
      sizeOptions: ["Large", "Medium", "Small"],
      weightOptions: ["1 kg", "100g", "2 kg", "250g", "500g"],
      browseOptions: ["All Products", "Okra", "Ugu", "Packaging"],
    },
    products: [
      {
        id: "prod-1",
        name: "Bio-degradable Produce Bags",
        price: 10,
        category: "Packaging",
        priceRange: "NGN 8-35",
        length: null,
        quantity: "10 Pack",
        size: null,
        weight: null,
        image: IMG.packaging,
        isPublished: true,
        sortOrder: 1,
      },
      {
        id: "prod-2",
        name: "Protective Produce Nets",
        price: 8,
        category: "Packaging",
        priceRange: "NGN 8-35",
        length: null,
        quantity: "25 Pack",
        size: null,
        weight: null,
        image: IMG.boxes,
        isPublished: true,
        sortOrder: 2,
      },
      {
        id: "prod-3",
        name: "Export Produce Box",
        price: 35,
        category: "Packaging",
        priceRange: "NGN 8-35",
        length: null,
        quantity: "10 Pack",
        size: null,
        weight: null,
        image: IMG.warehouse,
        isPublished: true,
        sortOrder: 3,
      },
      {
        id: "prod-4",
        name: "Dried Ugu Flakes",
        price: 22,
        category: "Ugu",
        priceRange: "NGN 8-35",
        length: null,
        quantity: null,
        size: "Small",
        weight: "100g",
        image: IMG.greens,
        isPublished: true,
        sortOrder: 4,
      },
      {
        id: "prod-5",
        name: "Ugu Seedlings",
        price: 18,
        category: "Ugu",
        priceRange: "NGN 8-35",
        length: null,
        quantity: "10 Seedlings",
        size: "Medium",
        weight: null,
        image: IMG.farm,
        isPublished: true,
        sortOrder: 5,
      },
      {
        id: "prod-6",
        name: "Fresh Ugu Leaves",
        price: 12,
        category: "Ugu",
        priceRange: "NGN 8-35",
        length: null,
        quantity: "20 Seedlings",
        size: "Large",
        weight: "250g",
        image: IMG.greens,
        isPublished: true,
        sortOrder: 6,
      },
      {
        id: "prod-7",
        name: "Fresh Okra",
        price: 8,
        category: "Okra",
        priceRange: "NGN 8-35",
        length: "100m",
        quantity: "10 Pack",
        size: "Medium",
        weight: "500g",
        image: IMG.okra,
        isPublished: true,
        sortOrder: 7,
      },
      {
        id: "prod-8",
        name: "Premium Okra",
        price: 35,
        category: "Okra",
        priceRange: "NGN 8-35",
        length: "200m",
        quantity: "25 Pack",
        size: "Large",
        weight: "2 kg",
        image: IMG.okra,
        isPublished: true,
        sortOrder: 8,
      },
    ],
  },
  portfolio: {
    pageTitle: "Portfolio",
    pageSubtitle: "Our export success stories and partnerships across Europe.",
    items: [
      {
        id: "port-1",
        title: "European Retail Partnership",
        description: "Premium okra supply chain for a major UK grocer — 12 tonnes weekly.",
        image: IMG.market,
        sortOrder: 1,
        isPublished: true,
      },
      {
        id: "port-2",
        title: "Ugu Export Program",
        description: "Year-round ugu leaves to Netherlands distributors with cold-chain logistics.",
        image: IMG.greens,
        sortOrder: 2,
        isPublished: true,
      },
      {
        id: "port-3",
        title: "Packaging Innovation",
        description: "Biodegradable export packaging rollout reducing plastic waste by 40%.",
        image: IMG.packaging,
        sortOrder: 3,
        isPublished: true,
      },
      {
        id: "port-4",
        title: "Farm Direct Sourcing",
        description: "Ethical cultivation partnerships across Southwest Nigeria.",
        image: IMG.farm,
        sortOrder: 4,
        isPublished: true,
      },
      {
        id: "port-5",
        title: "Cold Chain Excellence",
        description: "Rapid cooling and transit quality systems for 99.2% arrival freshness.",
        image: IMG.warehouse,
        sortOrder: 5,
        isPublished: true,
      },
      {
        id: "port-6",
        title: "Seasonal Specialties",
        description: "Curated seasonal produce for luxury retailers in Germany and France.",
        image: IMG.shopBanner,
        sortOrder: 6,
        isPublished: true,
      },
    ],
  },
  services: {
    pageTitle: "Our Services",
    pageSubtitle: "Book a consultation with our export specialists.",
    services: [
      {
        id: "svc-1",
        title: "Export Consultation",
        duration: "30 minutes",
        image: IMG.consultation,
        price: "₦25,000",
        description: "Discuss your import requirements, volumes, and product availability.",
        bookLabel: "Book Now",
        bookHref: "/book-online",
        isPublished: true,
        sortOrder: 1,
      },
      {
        id: "svc-2",
        title: "Quality Audit Walkthrough",
        duration: "45 minutes",
        image: IMG.meeting,
        price: "₦40,000",
        description: "Review our cultivation, packing, and export compliance processes.",
        bookLabel: "Book Now",
        bookHref: "/book-online",
        isPublished: true,
        sortOrder: 2,
      },
      {
        id: "svc-3",
        title: "Custom Sourcing Plan",
        duration: "60 minutes",
        image: IMG.logistics,
        price: "₦55,000",
        description: "Tailored produce sourcing and logistics plan for your market.",
        bookLabel: "Book Now",
        bookHref: "/book-online",
        isPublished: true,
        sortOrder: 3,
      },
    ],
  },
  blog: {
    pageTitle: "Blog",
    pageSubtitle: "News and insights from Eshmart Agrox.",
    posts: [
      {
        id: "post-1",
        title: "Exporting Nigerian Okra to Europe",
        slug: "exporting-nigerian-okra",
        excerpt:
          "What European buyers look for in premium okra — size, color, and compliance.",
        content:
          "European markets demand uniform size, vibrant color, and strict phytosanitary compliance.\n\nAt Eshmart Agrox, we work directly with farms in Ogun and Oyo states to ensure every crate meets EU standards. Our cold-chain partners maintain 4°C from packhouse to port.\n\nKey buyer requirements include:\n• Length uniformity within 2cm\n• Zero pesticide residues above MRL limits\n• Traceability documentation per batch\n\nContact our team for a sample shipment schedule.",
        coverImage: IMG.blog1,
        author: "Eshmart Team",
        publishedAt: now,
        isPublished: true,
        tags: ["okra", "export"],
      },
      {
        id: "post-2",
        title: "Why Ugu Is in Demand Abroad",
        slug: "ugu-demand-abroad",
        excerpt: "The rising appetite for Nigerian fluted pumpkin leaves in diaspora markets.",
        content:
          "Ugu (fluted pumpkin leaves) has seen 30% year-on-year growth in UK and EU ethnic grocery channels.\n\nWe flash-chill within 4 hours of harvest to preserve nutrients and shelf life. Our dried flake line offers an alternative for food manufacturers.\n\nRead on for packaging specs and MOQ details.",
        coverImage: IMG.blog2,
        author: "Ada Okafor",
        publishedAt: now,
        isPublished: true,
        tags: ["ugu", "market"],
      },
    ],
  },
  trackOrder: {
    pageTitle: "Track My Order",
    pageDescription: "Enter your order number to check shipment status.",
    orders: [
      {
        id: "ord-1",
        orderNumber: "EA-2026-001",
        customerName: "James Okonkwo",
        customerEmail: "james@example.com",
        status: "processing",
        items: [{ productName: "Fresh Okra", quantity: 2, price: 8 }],
        total: 16,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "ord-2",
        orderNumber: "EA-2026-002",
        customerName: "Maria Schmidt",
        customerEmail: "maria@example.de",
        status: "shipped",
        items: [{ productName: "Premium Okra", quantity: 5, price: 35 }],
        total: 175,
        createdAt: now,
        updatedAt: now,
      },
    ],
  },
};
